from enum import StrEnum, auto


class Planet(StrEnum):
    Serpulo = auto()
    Erekir = auto()


SectorNames = {
    Planet.Serpulo: {
        23: 'Biomass Synthesis Facility',
        41: 'Ruinous Shores',
        54: 'Cruxscape',
        64: 'Frozen Forest',
        65: 'Facility 32M',
        75: 'Atolls',
        85: 'Infested Canyons',
        86: 'Frontier',
        97: 'Windswept Islands',
        98: 'Salt Flats',
        99: 'Tar Fields',
        142: 'Overgrowth',
        143: 'Mycelial Bastion',
        145: 'Tainted Woods',
        164: 'Coastline',
        165: 'Naval Fortress',
        166: 'Weathered Channels',
        169: 'Testing Grounds',
        170: 'Ground Zero',
        173: 'Sunken Pier',
        204: 'Littoral Shipyard',
        213: 'Extraction Outpost',
        214: 'Perilous Harbor',
        217: 'Planetary Launch Terminal',
        219: 'Cratered Battleground',
        221: 'Fungal Pass',
        223: 'Stained Mountains',
        228: 'Nuclear Production Complex',
        264: 'Geothermal Stronghold',
        266: 'Impact 0078',
        271: 'Desolate Rift',
    },
    Planet.Erekir: {
        3: 'Crevice',
        5: 'Karst',
        10: 'The Onset',
        12: 'Origin',
        14: 'Atlas',
        18: 'Stronghold',
        19: 'Split',
        25: 'Marsh',
        29: 'Basin',
        30: 'Peaks',
        36: 'Intersect',
        37: 'Crossroads',
        39: 'Ravine',
        41: 'Lake',
        43: 'Caldera',
        58: 'Siege',
        88: 'Aegis',
    },
}

ItemIds = {
    Planet.Serpulo: [
        'blast-compound',
        'coal',
        'copper',
        'graphite',
        'lead',
        'metaglass',
        'phase-fabric',
        'plastanium',
        'pyratite',
        'sand',
        'scrap',
        'silicon',
        'thorium',
        'titanium',
        'spore-pod',
        'surge-alloy',
    ],
    Planet.Erekir: [
        'beryllium',
        'carbide',
        # 'dormant-cyst',
        # 'fissile-matter',
        'graphite',
        'oxide',
        'phase-fabric',
        'thorium',
        'tungsten',
        'sand',
        'silicon',
        'surge-alloy',
    ]
}

ItemColors = {
    'beryllium': '#3a8f64',
    'blast-compound': '#ff795e',
    'carbide': '#89769a',
    'coal': '#53565c', # Real: #272727
    'copper': '#d99d73',
    # 'dormant-cyst': '#df824d',
    # 'fissile-matter': '#5e988d',
    'graphite': '#b2c6d2',
    'lead': '#8c7fa9',
    'metaglass': '#ebeef5',
    'oxide': '#e4ffd6',
    'phase-fabric': '#f4ba6e',
    'plastanium': '#cbd97f',
    'pyratite': '#ffaa5f',
    'scrap': '#777777',
    'sand': '#f7cba4',
    'thorium': '#f9a3c7',
    'titanium': '#8da1e3',
    'tungsten': '#768a9a',
    'silicon': '#53565c',
    'spore-pod': '#7457ce',
    'surge-alloy': '#f3e979',
}